spin_manifest_version = 2

[application]
authors = ["markysoft <markharrop@yahoo.com>"]
description = ""
name = "spin-fs"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "spin-fs"

[component.spin-fs]
source = "target/spin-fs.wasm"
exclude_files = ["**/node_modules"]
[component.spin-fs.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]